export const SERVER_ACTIONS = {
  ADD_TEAM: "/add-team",
  GET_ALL_TEAMS: "/all-teams",
  GET_TEAM_PLAYERS: "/get-team-players",
  GET_TEAM_PLAYER_INFO:"/get-team-player-info",
  ADD_STADIUM: "/add-stadium",
  GET_ALL_STADIUMS: "/all-stadiums",
  GET_THE_STADIUM: "/get-stadium",
  ADD_BATTING_STYLE: "/add-batting-style",
  ADD_BOWLING_STYLE: "/add-bowling-style",
  ADD_ROLE: "/add-role",
  ADD_PLAYER_INFO: "/add-player-info",
};

export const PAGE_URLS = {
  HOME: "/",
  PAGE_NOT_FOUND: "**",
  ADMIN: "/admin",
  ADD_PLAYER_INFO: "/add-player-info",
  VIEW_TEAM_PLAYER_INFO: "/view-team-player-info/:id",
  ADD_PLAYER_STATS: "/add-player-stats",
  ADD_STADIUM: "/add-stadium",
  ADD_BATTING_STYLE: "/add-batting-style",
  ADD_BOWLING_STYLE: "/add-bowling-style",
  ADD_ROLE: "/add-role",
  ADD_TEAM: "/add-team",
  TEAMS_VIEW: "/teams-view",
  ALL_PLAYERS: "/all-players",
  ALL_STADIUMS: "/all-stadiums",
  VIEW_STADIUM: "/view-stadium/:id",
  TEAM_PLAYER_VIEW: "/view-team-players/:id",
  RECORDS: "/records",
  MOST_RUNS: "/most-runs",
  // TEMPORARY FOR VIEWING PUPOSES BEFORE ADDING ONCLICK FUNCTION
  VIEW_PLAYER_STATS: "/view-player-stats",
};
